version: '2'
volumes:
  home-data:
    external: true
services:
  prometheus:
    image: prom/prometheus
    #ports:
    #  - 9090:9090
    volumes:
      - home-data:/home-data
      - ./prometheus.yml:/home-data/prometheus/config/prometheus.yml:ro
    command: --config.file=/home-data/prometheus/config/prometheus.yml --storage.tsdb.path=/home-data/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles
    container_name:
      prometheus-server
    mem_limit: 128m
    cpu_quota: 50000
    restart: on-failure
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    container_name:
      grafana
    volumes:
      - home-data:/var/lib/grafana
    mem_limit: 128m
    cpu_quota: 50000
    restart: on-failure
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    container_name:
      mosquitto
    volumes:
      - home-data:/home-data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    mem_limit: 32m
    cpu_quota: 20000
  mqtt-exporter:
    build: ./mqtt_exporter_build
    image: mqtt_exporter:local
    container_name: 
      mqtt_exporter
    volumes:
      - ./mqtt_exporter/config:/mqtt_exporter/config:ro
    mem_limit: 64m
    cpu_quota: 10000
