# Example metric definition
metrics:
#  - name:     'mqtt_energy'                        # Required(unique, if multiple, only last entry is kept)
#    help:     'MQTT energy example'                  # Required
#    type:     'gauge'                               # Required ('gauge', 'counter', 'summary' or 'histogram')
#    #buckets:  '.1, 1.0, 10.0, inf'                 # Optional (Passed as 'buckets' argument to Histogram)
#    topic:    'SMA-EM/status/3002133445/+'                       # Required
#
#    # Inspired by 'https://prometheus.io/docs/operating/configuration/#<relabel_config>'
#    # "__msg_topic__" and "__value__" are populated with msg topic and value. And "__topic__" is 'topic' from config.
#    # Supported actions are: 'replace', 'keep' and 'drop'
#    # All labels starting with "__" will be removed, and "__topic__" and "__value__" is copied into "topic" anv "value"
#    # after all label configs have been applied.
#    label_configs:                                  # Optional
#      - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
#        separator:      '/'                         # Optional default ';'
#        regex:          '(.*)'                      # Optional default '(.*)'
#        target_label:   '__topic__'                   # Required (when label_configs is present and 'action' = 'replace')
#        replacement:    '\1'                        # Optional default '\1'
#        action:         'replace'                   # Optional default 'replace'

  - name: 'SMA_HM2_consume'
    help: 'consumption from public grid [W]'
    type: 'gauge'
    topic: 'SMA-EM/status/3002133445/pregard'

  - name: 'SMA_HM2_supply'
    help: 'supply into public grid [W]'
    type: 'gauge'
    topic: 'SMA-EM/status/3002133445/psurplus'

  - name: 'SMA_HM2_consume_p1'
    help: 'consumption from public grid [W] phase 1'
    type: 'gauge'
    topic: 'SMA-EM/status/3002133445/p1regard'

  - name: 'SMA_HM2_supply_p1'
    help: 'supply into public grid [W] phase 1'
    type: 'gauge'
    topic: 'SMA-EM/status/3002133445/p1surplus'

  - name: 'SMA_HM2_consume_p2'
    help: 'consumption from public grid [W] phase 2'
    type: 'gauge'
    topic: 'SMA-EM/status/3002133445/p2regard'

  - name: 'SMA_HM2_supply_p2'
    help: 'supply into public grid [W] phase 2'
    type: 'gauge'
    topic: 'SMA-EM/status/3002133445/p2surplus'

  - name: 'SMA_HM2_consume_p3'
    help: 'consumption from public grid [W] phase 3'
    type: 'gauge'
    topic: 'SMA-EM/status/3002133445/p3regard'

  - name: 'SMA_HM2_supply_p3'
    help: 'supply into public grid [W] phase 3'
    type: 'gauge'
    topic: 'SMA-EM/status/3002133445/p3surplus'
